# .github/workflows/ci.yml (Corrected)

name: CI Pipeline for Flight Price Prediction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This action checks out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This is the crucial fix: tells the action to fetch LFS files
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model tests
        run: pytest test_model.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Also fetch LFS files for the build job
          lfs: true

      - name: Build Docker image
        run: docker build -t flight-price-api .
