# .github/workflows/ci.yml (Final Version with Debugging)

name: CI Pipeline for Flight Price Prediction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Keep this just in case, it doesn't hurt

      # --- NEW DEBUGGING STEP ---
      - name: List files in the repository
        run: ls -lR

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model tests
        run: pytest test_model.py

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build Docker image
        run: docker build -t flight-price-api .
